[package]
name = "pyrepo"
version = "0.1.0"
edition = "2021"


[dependencies]
configmodel = { path = "../../../../lib/config/model" }
cpython_ext = { path = "../../../../lib/cpython-ext" }
cpython = { version = "0.7", default-features = false }
repo = { path = "../../../../lib/repo" }
repolock = { path = "../../../../lib/repolock" }
util = { path = "../../../../lib/util" }
parking_lot = "0.12.1"
pyconfigloader = { path = "../pyconfigloader" }
pydag = { path = "../pydag" }
pyeagerepo = { path = "../pyeagerepo" }
pyedenapi = { path = "../pyedenapi" }
pymetalog = { path = "../pymetalog" }
pyrevisionstore = { path = "../pyrevisionstore" }
pyworkingcopy = { path = "../pyworkingcopy" }
revisionstore = { path = "../../../../lib/revisionstore" }
workingcopy = { path = "../../../../lib/workingcopy" }
